contigs: ../Steno_phage_output/phage_contigs_all/
customDatabaseDirectory: databases
input: ../Steno_bacteria
outdir: output
output: ../crassphage
phage: ../crassphage/phage_finalset
sequencing: longread
temp_dir: tmp
