contigs: ../Steno_phage_output/phage_contigs_all/
customDatabaseDirectory: databases
input: ../Steno_bacteria
outdir: output
output: ../salmonella
phage: ../salmonella/phage-final
sequencing: longread
temp_dir: tmp
